# Generated by Django 4.2.1 on 2023-05-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_alter_branch_options_alter_city_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "Branch", "verbose_name_plural": "Branches"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["district"],
                "verbose_name": "Cities",
                "verbose_name_plural": "City",
            },
        ),
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ["name"],
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
            },
        ),
        migrations.AlterModelOptions(
            name="state",
            options={
                "ordering": ["name"],
                "verbose_name": "State",
                "verbose_name_plural": "States",
            },
        ),
    ]
