# Generated by Django 4.2.1 on 2023-05-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_alter_branch_options_alter_city_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["name"],
                "verbose_name": "Cities",
                "verbose_name_plural": "City",
            },
        ),
        migrations.RemoveField(model_name="city", name="district",),
        migrations.RemoveField(model_name="district", name="state",),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.state",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="branch", name="mobile", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="branch", name="pincode", field=models.IntegerField(),
        ),
    ]
