# Generated by Django 4.2.1 on 2023-05-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_alter_city_options_remove_city_district_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AddField(
            model_name="district",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.state",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="settings.branch"
            ),
        ),
    ]
