# Generated by Django 4.2.1 on 2023-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_alter_course_options_district_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("Startdate", models.DateField()),
                ("Enddate", models.DateField()),
                ("active", models.BooleanField(default=True)),
                ("closed", models.BooleanField(default=False)),
            ],
            options={"verbose_name": "Batch", "verbose_name_plural": "Batches",},
        ),
        migrations.RemoveField(model_name="course", name="branch",),
        migrations.AddField(
            model_name="course",
            name="coursecode",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
