# Generated by Django 4.2.1 on 2023-05-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_batch_remove_course_branch_course_coursecode"),
    ]

    operations = [
        migrations.RemoveField(model_name="city", name="state",),
        migrations.AddField(
            model_name="city",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.district",
            ),
            preserve_default=False,
        ),
    ]
