# Generated by Django 4.2.1 on 2023-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0007_remove_city_state_city_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="trainer",
            field=models.CharField(
                choices=[("2", "Vrindha"), ("1", "Neethu")], default=1, max_length=15
            ),
            preserve_default=False,
        ),
    ]
