# Generated by Django 4.2.1 on 2023-05-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0008_batch_trainer"),
    ]

    operations = [
        migrations.RemoveField(model_name="batch", name="active",),
        migrations.RemoveField(model_name="batch", name="closed",),
        migrations.AlterField(
            model_name="batch",
            name="trainer",
            field=models.CharField(
                choices=[("1", "Neethu"), ("2", "Vrindha")], max_length=15
            ),
        ),
    ]
