# Generated by Django 4.2.1 on 2023-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_remove_batch_active_remove_batch_closed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="district", old_name="state", new_name="State",
        ),
        migrations.AlterField(
            model_name="batch",
            name="trainer",
            field=models.CharField(
                choices=[("2", "Vrindha"), ("1", "Neethu")], max_length=15
            ),
        ),
    ]
