# Generated by Django 4.2.1 on 2023-06-03 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0013_course_course_fees_alter_batch_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_fees",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.course_fees",
            ),
        ),
    ]
