# Generated by Django 4.2.1 on 2023-06-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0016_alter_batch_trainer_alter_course_course_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="trainer",
            field=models.CharField(
                choices=[("2", "Vrindha"), ("1", "Neethu")], max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_fees",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.course_fees",
            ),
        ),
    ]
