# Generated by Django 4.2.1 on 2023-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_alter_batch_trainer_alter_course_course_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="trainer",
            field=models.CharField(
                choices=[("1", "Neethu"), ("2", "Vrindha")], max_length=15
            ),
        ),
    ]
