# Generated by Django 4.2.1 on 2023-06-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0019_alter_batch_trainer"),
    ]

    operations = [
        migrations.RemoveField(model_name="batch", name="name",),
        migrations.AddField(
            model_name="batch",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="settings.course",
            ),
            preserve_default=False,
        ),
    ]
