# Generated by Django 4.2.1 on 2023-06-05 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("settings", "0020_remove_batch_name_batch_course"),
    ]

    operations = [
        migrations.RemoveField(model_name="batch", name="trainer",),
        migrations.AddField(
            model_name="course",
            name="trainer",
            field=models.ManyToManyField(
                related_name="courses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
