# Generated by Django 4.2.1 on 2023-06-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0022_alter_course_fees_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="course_fees",),
        migrations.AddField(
            model_name="course_fees",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="settings.course",
            ),
            preserve_default=False,
        ),
    ]
