# Generated by Django 4.2.1 on 2023-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0023_remove_course_course_fees_course_fees_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch", name="status", field=models.BooleanField(default=False),
        ),
    ]
