# Generated by Django 4.2.1 on 2023-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0025_remove_batch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch", name="status", field=models.BooleanField(default=False),
        ),
    ]
