# Generated by Django 4.2.1 on 2023-06-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_student_course"),
        ("settings", "0026_batch_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.BooleanField(
                choices=[(True, "Active"), (False, "Closed")], default=False
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("payment_date", models.DateField(auto_now_add=True)),
                (
                    "std_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="students.student",
                    ),
                ),
            ],
            options={"verbose_name": "Payment", "verbose_name_plural": "Payments",},
        ),
    ]
