# Generated by Django 4.2.2 on 2023-06-15 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_photo'),
        ('settings', '0027_alter_batch_status_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='std_name',
            new_name='std_name_P',
        ),
        migrations.AlterField(
            model_name='course_fees',
            name='fees_type',
            field=models.CharField(choices=[('one_times', 'One Time'), ('two_times', 'Two Times'), ('three_times', 'Three Times')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FeesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('receipt_number', models.CharField(max_length=50)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_to_account', models.CharField(choices=[('oneteam ac 1', 'Oneteam ac 1'), ('oneteam ac 2', 'Oneteam ac 2'), ('oneteam ac 3', 'Oneteam ac 3')], max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=50)),
                ('description', models.TextField()),
                ('receipt_image', models.ImageField(upload_to='receipts/')),
                ('std_name_FR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('one_times', 'One Time'), ('two_times', 'Two Times'), ('three_times', 'Three Times')], max_length=20, null=True)),
                ('first_pay', models.DateField(blank=True, null=True)),
                ('first_pay_amount', models.IntegerField(blank=True, null=True)),
                ('second_pay', models.DateField(blank=True, null=True)),
                ('second_pay_amount', models.IntegerField(blank=True, null=True)),
                ('third_pay', models.DateField(blank=True, null=True)),
                ('third_pay_amount', models.IntegerField(blank=True, null=True)),
                ('std_name_FD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students.student')),
            ],
        ),
    ]
