# Generated by Django 4.2.2 on 2023-06-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_has_laptop_student_joining_date_and_more'),
        ('settings', '0029_rename_std_name_fd_feedetails_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstallmentDate', models.DateField()),
                ('InstallmentAmount', models.IntegerField()),
                ('BalanceAmount', models.IntegerField()),
                ('taxper', models.IntegerField(blank=True, null=True, verbose_name='Tax Per.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
