# Generated by Django 4.2.2 on 2023-06-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_alter_course_fees_fees_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_fees',
            name='fees_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_fees', to='settings.course_fees'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
