# Generated by Django 4.2.2 on 2023-06-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_student_course_fees_student_fees_type'),
        ('settings', '0037_alter_course_fees_fees_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_fees',
            name='fees_type',
            field=models.ForeignKey(choices=[('Registration', 'Registration'), ('one_times', 'One Time'), ('two_times', 'Two Times'), ('three_times', 'Three Times')], max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_fees', to='settings.course_fees'),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.student'),
        ),
    ]
