# Generated by Django 4.0.2 on 2023-05-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=20)),
                ('alternative_email', models.EmailField(max_length=20)),
                ('address', models.TextField(max_length=20)),
                ('alternative_address', models.TextField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gender')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.city')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.course')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.state')),
            ],
        ),
    ]
