# Generated by Django 4.0.2 on 2023-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Gender',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='exit', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
