# Generated by Django 4.2.1 on 2023-05-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_mobile_alter_student_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "student", "verbose_name_plural": "Students"},
        ),
    ]
