# Generated by Django 4.2.1 on 2023-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterField(
            model_name="student", name="mobile", field=models.CharField(max_length=10),
        ),
    ]
