# Generated by Django 4.2.1 on 2023-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_student_options_alter_student_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="alternative_address",
            field=models.TextField(max_length=200),
        ),
    ]
