# Generated by Django 4.2.1 on 2023-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_alter_student_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
    ]
