# Generated by Django 4.2.1 on 2023-06-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0023_remove_course_course_fees_course_fees_course"),
        ("students", "0008_student_is_active_student_is_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="settings.course"
            ),
        ),
    ]
