# Generated by Django 4.2.1 on 2023-06-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_student_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/admin/img"
            ),
        ),
    ]
