# Generated by Django 4.2.2 on 2023-06-15 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_rename_std_name_payment_std_name_p_and_more'),
        ('students', '0010_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_laptop',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, default='2012-12-12', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.city'),
        ),
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.district'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.state'),
        ),
    ]
