# Generated by Django 4.2.2 on 2023-06-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_studentfees'),
        ('students', '0011_student_has_laptop_student_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='settings.batch'),
            preserve_default=False,
        ),
    ]
