# Generated by Django 4.2.2 on 2023-06-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_studentfees'),
        ('students', '0013_student_end_date_student_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_fees',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.course_fees'),
            preserve_default=False,
        ),
    ]
