# Generated by Django 4.2.2 on 2023-06-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_course_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_fees',
        ),
    ]
