# Generated by Django 4.2.2 on 2023-06-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_studentfees'),
        ('students', '0015_remove_student_course_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.course_fees'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.course'),
        ),
    ]
