# Generated by Django 4.2.2 on 2023-06-20 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_studentfees'),
        ('students', '0016_student_course_fees_alter_student_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_fees',
        ),
        migrations.AddField(
            model_name='student',
            name='fees_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='settings.course_fees'),
        ),
    ]
